# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_win(object):
    def setupUi(self, main_win):
        main_win.setObjectName("main_win")
        main_win.resize(725, 484)
        self.centralwidget = QtWidgets.QWidget(main_win)
        self.centralwidget.setObjectName("centralwidget")
        self.photo_files = QtWidgets.QPushButton(self.centralwidget)
        self.photo_files.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.photo_files.setObjectName("photo_files")
        self.photo_list = QtWidgets.QListWidget(self.centralwidget)
        self.photo_list.setGeometry(QtCore.QRect(20, 70, 131, 311))
        self.photo_list.setObjectName("photo_list")
        self.photo_lab = QtWidgets.QLabel(self.centralwidget)
        self.photo_lab.setGeometry(QtCore.QRect(180, 20, 521, 311))
        self.photo_lab.setStyleSheet("background-color:grey;")
        self.photo_lab.setText("")
        self.photo_lab.setObjectName("photo_lab")
        self.left_btn = QtWidgets.QPushButton(self.centralwidget)
        self.left_btn.setGeometry(QtCore.QRect(180, 360, 75, 23))
        self.left_btn.setObjectName("left_btn")
        self.right_btn = QtWidgets.QPushButton(self.centralwidget)
        self.right_btn.setGeometry(QtCore.QRect(270, 360, 75, 23))
        self.right_btn.setObjectName("right_btn")
        self.mirrow_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mirrow_btn.setGeometry(QtCore.QRect(360, 360, 75, 23))
        self.mirrow_btn.setObjectName("mirrow_btn")
        self.blur_btn = QtWidgets.QPushButton(self.centralwidget)
        self.blur_btn.setGeometry(QtCore.QRect(450, 360, 75, 23))
        self.blur_btn.setObjectName("blur_btn")
        self.white_black_btn = QtWidgets.QPushButton(self.centralwidget)
        self.white_black_btn.setGeometry(QtCore.QRect(540, 360, 75, 23))
        self.white_black_btn.setObjectName("white_black_btn")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(630, 360, 75, 23))
        self.save_btn.setObjectName("save_btn")
        main_win.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 21))
        self.menubar.setObjectName("menubar")
        main_win.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_win)
        self.statusbar.setObjectName("statusbar")
        main_win.setStatusBar(self.statusbar)

        self.retranslateUi(main_win)
        QtCore.QMetaObject.connectSlotsByName(main_win)

    def retranslateUi(self, main_win):
        _translate = QtCore.QCoreApplication.translate
        main_win.setWindowTitle(_translate("main_win", "Photo_redactor"))
        self.photo_files.setText(_translate("main_win", "Папка"))
        self.left_btn.setText(_translate("main_win", "Вліво"))
        self.right_btn.setText(_translate("main_win", "Вправо"))
        self.mirrow_btn.setText(_translate("main_win", "Дзеркало"))
        self.blur_btn.setText(_translate("main_win", "Різкість"))
        self.white_black_btn.setText(_translate("main_win", "Ч/Б"))
        self.save_btn.setText(_translate("main_win", "Зберегти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_win = QtWidgets.QMainWindow()
    ui = Ui_main_win()
    ui.setupUi(main_win)
    main_win.show()
    sys.exit(app.exec_())
